name: Backend CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
defaults:
  run:
    working-directory: ./server

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Backend Install dependencies
      run: npm ci
      working-directory: ./server
      
    - name: Backend Build
      run: npm run build
      working-directory: ./server
      
    - name: Backend Lint
      run: npm run lint
      working-directory: ./server
      
    - name: Backend Unit Test 
      run: npm run test
      working-directory: ./server
