name: Backend CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

defaults:
  run:
    working-directory: ./server

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./server/package-lock.json

      - name: Backend Install dependencies
        run: npm ci

      - name: Backend Build
        run: npm run build

      - name: Backend Lint
        run: npm run lint

      - name: Backend Unit Test
        run: npm run test
